### ISSUE TITLE
Issue with React 16.3

### ISSUE THREAD

**Issue by khawerrind** [romainberger/react-portal-tooltip#81]
Hi, thank you for the great plugin. I am getting the following error sometime 

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at ToolTip.componentWillUnmount 
```

react: 16.6.3
react-dom: 16.6.3
react-portal-tooltip: 2.4.1

**Comment by JZBo** [comment]
Hello,

I can confirm the issue, I'm having the same kind of error, which seems to occur after redux store updates change the way a component should render.

With react and react-dom: 16.6.3 and react-portal-tooltip: 2.4.1 the issue exists.
Reverting to react-portal-tooltip: 2.3.0 apparently solves the issue for the time being.

Kind regards.

**Comment by kblcuk** [comment]
Error stack points to the line added [in this commit](https://github.com/romainberger/react-portal-tooltip/commit/9996cfbb9bbf46755699c7c42ab15d19f6652a68)

**Comment by mean2me** [comment]
Hello,

do you think that introducing an existence check before to any attempt to remove  that element would be enough?

**Comment by sebastianescribano** [comment]
Hello, I am having the same problem and I made a rollback to previous version to fix it

**Comment by romainberger** [comment]
Hi, I've pushed and published a new version that should fix all issues with react 16.6.3. Please let me know if you have more issues. Thanks

**Comment by JZBo** [comment]
I had the occasion to try it, but unfortunately the issue is not completely fixed, at least not in all the use cases, although it is improved.

Using react-portal-tooltip v2.4.3 causes tooltips not to be rendered when using a css-in-js library like fela. Tooltips are NOT rendered, and it's like they are missing their context.

The error reported is:
Uncaught Error: createComponent() can't render styles without the renderer in the context. Missing react-fela's <Provider /> at the app root?  at FelaComponent (createComponentFactory.js:43) ...

Everything is still working perfectly with react-portal-tooltip 2.3.0.

Obviously, said styling library is not part of this package, but I thought it useful to report it. This looks very similar to the original error which occurred when redux-connected component were updated. As in that case, it looks like the original components are 'vanishing' from their provider context, and thus the styling service breaks down.

**Comment by romainberger** [comment]
I don't know fela and I've only tested the tooltip with no other modules than react itself, I'll try to see if I can find something. 
When fixing the issue I updated the module to support the lifecycle changes in the new react versions, it might be the source of the issue.
